# Name of the speller package in various languages.
# The default is English + autonym:
[speller.name]
en = "Esperanto spellchecker"
eo = "Autonym spellchecker"

# Description of the speller package in various languages.
# The default is English + autonym:
[speller.description]
en = "A spellchecker for Esperanto, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"
eo = "TRANSLATE: A spellchecker for Esperanto, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"

[macos]
system_pkg_id = "no.divvun.MacDivvun.eo"

[windows]
system_product_code = "{C9D89BC1-1D77-433E-90A3-2D2D4C1BF25F}_is1"
legacy_product_codes = [
    { value = "9DE25003-A6A4-4115-8E2E-5720A6B66E43", kind = "nsis" },
    { value = "C3AB23AA-09BD-4A48-9FDC-CFF4B4403696", kind = "nsis" }
]

[package.speller]
name = "Esperanto"
version = "0.1.1"

[package.grammar]
name = "Esperanto"
version = "0.1.0"

[package.tts-text-proc]
name = "Esperanto"
version = "0.1.0"
