template = "https://github.com/giellalt/template-lang-und"
rev_id = 257
template_sha = "0b3fb3d8836831dedcfe3f4b9fcdc3e2aef12fa5"

[replacements]
__GLOTTOLOG_ID__ = "espe1235"
__REPO__ = "lang-epo"
__UND2C__ = "eo"
__UNDEFINED__ = "Esperanto"
__UND__ = "epo"
