template = "https://github.com/giellalt/template-lang-und"
rev_id = 267
template_sha = "eecc8ba78a1297394fa54b425d94002ee6604eb1"

[replacements]
__GLOTTOLOG_ID__ = "espe1235"
__REPO__ = "lang-epo"
__UND2C__ = "eo"
__UNDEFINED__ = "Esperanto"
__UND__ = "epo"
